mutation RunProductColorMigrationInventory {
  bulkOperationRunQuery(
    query: """
    {
      products {
        edges {
          node {
            id
            title
            handle
            legacyHiddenColors: metafield(namespace: "custom", key: "farben_ausblenden") {
              jsonValue
            }
            legacyDefaultTextColor: metafield(namespace: "custom", key: "default_text_farbe") {
              jsonValue
            }
            legacyDefaultDecorationColor2: metafield(namespace: "custom", key: "default_deko_2_farbe") {
              jsonValue
            }
            hiddenColors: metafield(namespace: "custom", key: "hidden_colors") {
              jsonValue
            }
            defaultTextColor: metafield(namespace: "custom", key: "default_text_color") {
              jsonValue
            }
            defaultDecorationColor1: metafield(namespace: "custom", key: "default_decoration_color_1") {
              jsonValue
            }
            defaultDecorationColor2: metafield(namespace: "custom", key: "default_decoration_color_2") {
              jsonValue
            }
          }
        }
      }
    }
    """
  ) {
    bulkOperation {
      id
      status
    }
    userErrors {
      field
      message
    }
  }
}
